### ISSUE TITLE
Follow Location

### ISSUE THREAD

**Issue by jose46moreno** [ricardojoserf/instagram-followers-bot#11] opened 2020-06-05 13:12 UTC
Hello Ricardo,

I wanted to ask you a question. I'm using the command to follow from a location and it never interacts with more than 8 or 10 users.

Is there any limitation you have set in the code?

For id 213870197 which is Cordoba, this is the list of users I have interacted with.

<img width="362" alt="Captura de pantalla 2020-06-05 a las 15 12 46" src="https://user-images.githubusercontent.com/8105593/83880140-06f94880-a73f-11ea-8dc9-9920da2ecb64.png">

**Comment by ricardojoserf** [comment] 2020-06-06 16:25
Hi @jose46moreno ! I have not played with the Intagram API for a while, but I think that is part of its functionality (I mean, I did not add any limitation based on the location). Does it work the same in other places? I will make some tests now anyways, just in case you had already done it.

**Comment by ricardojoserf** [comment] 2020-06-06 16:34
Hi again @jose46moreno , I just read the code again and it has only one limitation: the variable MAXIMO in line 12, but it is set to 100 so it should not be the problem here. So I assume your problem is caused by the functionality of the Instagram API. Tell me if I can help with any other thing or I can close the issue :)

**Closed** 2020-06-15 06:39 UTC
