### ISSUE TITLE
It shows the error

### ISSUE THREAD

**Issue by eraliev** [ricardojoserf/instagram-followers-bot#2] opened 2018-07-25 21:22 UTC
File "main.py", line 86
    print "Following " + username
                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Following " + username)?

**Comment by ricardojoserf** [comment] 2018-07-26 18:35
Hello erakiev. Probably it is because you are running it using Python3, with needs parenthesis. Try running with Python 2 and tell me if it works :)

**Comment by eraliev** [comment] 2018-07-28 05:17
Hi, i have tried to running with pyton2, but it shows this error -"instagram-followers-bot-master\LevPasha\InstagramAPI.py", line 164, in getTotalSelfFollowers
    return self.getTotalFollowers(self.username_id)
AttributeError: InstagramAPI instance has no attribute 'username_id' "

**Comment by ricardojoserf** [comment] 2018-07-28 08:39
Are you trying something similar to "python main.py -u USERNAME -p PASSWORD -o follow-tag -t cat"? Or what command are you trying?

**Comment by eraliev** [comment] 2018-07-31 17:58
yes, i have several versions of python, path version is python 2.7 another version is py -3 (python 3) should i delete python 3?

**Comment by ricardojoserf** [comment] 2019-01-08 19:39
I checked it now and it does not show any error. Please @eraliev tell me if it still happens :)

**Comment by ricardojoserf** [comment] 2019-01-15 08:57
Hello, as the problem is solved and i did not receive an answer in one week, i will close the issue.
Thank you! :)

**Closed** 2019-01-15 08:58 UTC
